Repository wuespace/telestion-docs, pull requests merged in 2022-02, with the labels that each got.

#170 chore(main): release 2.6.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#173 Fix configuration base interfaces
  docs/application/tutorials/202-adding-configuration-options.mdx
Labels: bug, documentation

#174 chore(main): release 2.6.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#176 feat(stylesheet): :lipstick: Add dark mode support
  docs/index.mdx
  docusaurus.config.js
  src/css/custom.css
Labels: enhancement

#184 feat(docs/client): :sparkles: Add "TypeScript" concept
  docs/client/concepts/115-typescript.mdx
Labels: documentation, enhancement

#183 feat(docs/client): :sparkles: Add React concept
  docs/client/concepts/130-react.mdx
Labels: documentation, enhancement

#193 Add manual steps to initialize a Telestion Project
  docs/application/tutorials/100-starting-a-new-project.mdx
Labels: enhancement
