Repository wuespace/telestion-docs, pull requests merged in 2022-01, with the labels that each got.

#149 chore(main): release 2.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#155 feat(docs/client): :sparkles: Add Electron concept
  docs/client/concepts/120-electron.mdx
  docs/client/concepts/index.mdx
Labels: enhancement

#160 Web Client dialog tutorials
  docs/client/tutorials/300-writing-a-static-dialog.mdx
  docs/client/tutorials/301-writing-a-stateful-dialog.mdx
  static/img/dialogs/simple-dialog-open-dialog.png
  static/img/dialogs/simple-dialog-structure.png
  static/img/dialogs/stateful-dialog-dev-console.png
  static/img/dialogs/stateful-dialog-layout.png
  static/img/dialogs/stateful-dialog-options-dialog.png
Labels: enhancement

#162 Update Verticle documentation
  .github/workflows/ci.yml
  .vale.ini
  docs/_templates/guide.mdx
  docs/application/concepts/110-verticle.mdx
  docs/application/concepts/130-traits.mdx
  docs/application/guides/200-writing-your-own-traits.mdx
  docs/application/tutorials/200-writing-a-verticle.mdx
  docs/application/tutorials/201-using-jsonmessage.mdx
  docs/application/tutorials/202-adding-configuration-options.mdx
  docs/application/tutorials/203-using-traits-in-verticles.mdx
  docs/client/tutorials/100-dev-env-setup.mdx
  docs/client/tutorials/200-bootstrapping-a-widget.mdx
  docs/internal/concepts/conventional-commits.mdx
  docs/internal/references/conventional-commit-types.mdx
  package-lock.json
  package.json
  vale-styles/Vocab/Docs/accept.txt
Labels: enhancement

#156 chore(main): release 2.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#167 chore(main): release 2.6.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#168 fix(docs/application): Fix formatting in "Using Traits in Verticles" tutorial
  docs/application/tutorials/203-using-traits-in-verticles.mdx
Labels: bug
